<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Application' => $baseDir . '/core/Application.php',
    'CandidatRepository' => $baseDir . '/eonea/repository/CandidatRepository.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Controller' => $baseDir . '/core/Controller.php',
    'Database' => $baseDir . '/core/Database.php',
    'DiplomeRepository' => $baseDir . '/eonea/repository/DiplomeRepository.php',
    'Dompdf\\Cpdf' => $vendorDir . '/dompdf/dompdf/lib/Cpdf.php',
    'EmploisRepository' => $baseDir . '/eonea/repository/EmploisRepository.php',
    'Normalizer' => $vendorDir . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    'adminController' => $baseDir . '/eonea/controllers/adminController.php',
    'eoneaController' => $baseDir . '/eonea/controllers/eoneaController.php',
);
